### ISSUE TITLE
Unable to deploy stack in portainer

### ISSUE THREAD

**Issue by YouDoMeIDoYou** [MisterCalvin/dxhx-coop-server#2]
Hi MisterCalvin, thanks for providing a dxhx coop-server on GitHub!
Unfortunately I cannot deploy your container stack inside portainer.

Here's my compose file:
```
services:
  dxhx-coop-server:
    image: ghcr.io/mistercalvin/dxhx-coop-server:latest
    container_name: dxhx-coop-server
    environment:
      - "PUID=1000" # Optional: Set the UID for the user inside the container; Default: 1000
      - "PGID=1000" # Optional: Set the GID for the user inside the container; Default: 1000
      - "SERVER_NAME=" # Optional: Name of your server; Default: Another Docker HX Coop Server
      - "SERVER_PASSWORD=" # Optional: Server password. Clients will need the DXMTL mod installed to enter passwords, or type the following in console: open <youripaddress>:<port>?password=<password> in order to connect; Default: unset
      - "SERVER_PORT=" # Optional: Port the Server will listen on; Default: 7990
      - "SERVER_INI=" # Optional: Specify a custom server configuration file; Default: unset
      - "ADMIN_PASSWORD=" # Optional: Admin password (if empty admin login will be disabled); Default: unset
      - "MAP=00_Training" # Optional: Map to play; Default: 00_Training
      - "MUTATORS=" # Optional: A comma-separated list of Mutators to load; Default: unset
      - "MAX_PLAYERS=8" # Optional, Max Players for the server; Default: 8
      - "DIFFICULTY=1" # Optional: Specify game difficulty, 0 = Easy, 1 = Medium, 2 = Hard, or 3 = DeusEx (Realistic); Default: 1 (Medium)
      - "ADDITIONAL_ARGS=" # Optional: Pass additional arguments such as multihome or specify a custom log file; Default: unset
      - "DX_RANDOMIZER=False" # Optional: Enable DX Randomizer mod (will also download mod if not available in game folder); Default: False
      - "DX_DEATHMARKERS=True" # Optional: Death Markers show you where other players have died, using a skull icon. It also tells you how they died and when (only for DX Randomizer); Default: True
      - "DX_ENABLE_TELEMETRY=False" # Optional: Enable Online Features for DX Randomizer, including posting in-game events to their Mastodon bot, updating their death marker database, and leaderboards; Default: False
      - "DX_GAMEMODE=0" # Optional: Gamemode for DX Randomizer (0 = Normal, 1 = Randomizer Lite, 2 = Zero Rando, 3 = Serious Sam Mode, 4 = Speedrun Mode, 5 = WaltonWare); Default: 0 (Normal)
      - "DX_LOADOUT=0" # Optional: Choose the load for DX Randomizer (0 = All Items Allowed, 1 = Prod Plus, 2 = Prod Pure, 3 = Ninja JC, 4 = By the Book, 5 = No Overpowered, 6 = Don't Give me the GEP Gun, 7 = No Pistaols, 8 = No Swords, 9 = Grenades Only, 10 = Freeman Mode; Default = 0 (All Items Allowed))
      - "DX_AUTOUPDATE=True" # Optional: Grab latest version of DX Randomizer on each container boot. See disclaimers in README.md; Default: True
    volumes:
      - /opt/dxhx/gamefiles/:container/deusex
      - dxhx-coop-wine:/container/.wine
    ports:
      - 7990-7992:7990-7992/udp
    restart: unless-stopped

volumes:
  dxhx-coop-wine:
    name: dxhx-coop-wine
```
Inside the previously created folder `/opt/dxhx/gamefiles/` I copied the untouched DeusEx Folders:
- GOTY_1
- Maps
- Music
- Sounds
- System

When deploying in portainer I get the following message:
```
failed to deploy a stack: Network dxhx_default Creating Network dxhx_default Created Container dxhx-coop-server Creating Error response from daemon: invalid volume specification: '/opt/dxhx/gamefiles/:container/deusex:rw': invalid mount config for type "bind": invalid mount path: 'container/deusex' mount path must be absolute
```
I must admint that I'm quite new to that docker stuff but maybe you can help me out - thanks!
